### ISSUE TITLE
セルの原点位置について

### ISSUE THREAD

**Issue by G-mode** [SpriteStudio/PSDtoSS#1]
要望です。
セルの原点位置を変えた時にssae側で、オブジェクトがずれるのではなく、オブジェクトの位置はそのままで座標だけかわるようにして欲しいです。さらにセル編集時にどちらか選べるようにしてほしいです。

**Comment by SpriteStudio** [comment]
要望ありがとうございます。
SS5本体の次バージョン5.5のアップデートにて、原点編集時に見た目を固定できる機能を予定しておりますので今しばらくお待ちください。
よろしくお願いいたします。

**Comment by G-mode** [comment]
返答有難うございます。
アップデート心待ちにしております。
よろしくお願いします。

**Comment by DKAlpha** [comment]
今たせしました。SS5.5のアップデートが配信となりました。
原点の変更時にレイアウトを維持する機能が追加されておりますのでお試しください。

**Comment by G-mode** [comment]
ご連絡ありがとうございます。
試させていただきたいと思います。
