### ISSUE TITLE
v1.0.5　出力されたssceファイルをss5に登録しようとするとエラーが出ます。

### ISSUE THREAD

**Issue by kgtkrtykn** [SpriteStudio/PSDtoSS#14]
コンバートしたssceファイルをss5のプロジェクトに登録しようとすると
「ファイルが開けません　xxxxxxxx.png」というエラーが出て画像を登録できません。
セルリストを見ると紫色の四角い画像でセルが登録された状態になっており、
それぞれのサイズ・レイヤー名は正しく読み込まれているようですが
肝心の画像そのものが読み込まれません。

PhotoShopCC2015・win7-64bit環境です。

**Comment by kgtkrtykn** [comment]
自己解決しました
失礼しました

**Comment by DKAlpha** [comment]
参考までに、どのような事が原因だったのか共有していただく事はできますでしょうか？
