### ISSUE TITLE
whitesquareの問題、　別のアニメファイルとの合体

### ISSUE THREAD

**Issue by kimyunmi** [SpriteStudio/PSDtoSS#16]
１．http://www.webtech.co.jp/help/effect_whitesquare
以前質問させて頂いた部分ですが、パージが表示されないんで解決して頂きたいです。

２．他のSSPJにあるアニメを合体したいんですが、できる方法ありませんか？

**Comment by DKAlpha** [comment]
申し訳ございませんが、こちらはPSDtoSSについての問い合わせのみ受け付けております。
SpriteStudiono本体についての問い合わせは、こちらの問い合わせページ
http://www.webtech.co.jp/help/ja/spritestudio/inquiries/
から問い合わせしていたければと思います。

申し訳ございませんがこちらのIssueはクローズといたします。
